# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 088a8a07328cf9d6b1c4cd461bb25d5b23fc3a40b9505242f33f5cae568999102b11ab826c7a0a3e1bbc092d71a34a3c33637ac00536b4ec0480053efbe16f3c

test:
  secret_key_base: 2f27e5b7f714893c4ce84d750576e12320a781684a931ae8141e36fb19145ab17b0952434cee16ac7e1af52e16a496a450fadce91e09b191964a7ff4a3f041af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
